/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AppTodo {
    'tarefas': Array<{ feito: boolean; descricao: string }>;
  }
  interface TodoContainer {
    'saudacao': () => Promise<void>;
  }
}

declare global {


  interface HTMLAppTodoElement extends Components.AppTodo, HTMLStencilElement {}
  var HTMLAppTodoElement: {
    prototype: HTMLAppTodoElement;
    new (): HTMLAppTodoElement;
  };

  interface HTMLTodoContainerElement extends Components.TodoContainer, HTMLStencilElement {}
  var HTMLTodoContainerElement: {
    prototype: HTMLTodoContainerElement;
    new (): HTMLTodoContainerElement;
  };
  interface HTMLElementTagNameMap {
    'app-todo': HTMLAppTodoElement;
    'todo-container': HTMLTodoContainerElement;
  }
}

declare namespace LocalJSX {
  interface AppTodo {
    'onEmiteTotal'?: (event: CustomEvent<any>) => void;
    'tarefas'?: Array<{ feito: boolean; descricao: string }>;
  }
  interface TodoContainer {}

  interface IntrinsicElements {
    'app-todo': AppTodo;
    'todo-container': TodoContainer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-todo': LocalJSX.AppTodo & JSXBase.HTMLAttributes<HTMLAppTodoElement>;
      'todo-container': LocalJSX.TodoContainer & JSXBase.HTMLAttributes<HTMLTodoContainerElement>;
    }
  }
}


